name: ci

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-memfill:
    name: Build memfill
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Build
        run: |
          cargo install cross --git https://github.com/cross-rs/cross
          make build

      - if: startsWith(github.ref, 'refs/tags/')
        run: |
          cp ./target/x86_64-unknown-linux-gnu/release/memfill ./target/memfill.amd64
          cp ./target/aarch64-unknown-linux-gnu/release/memfill ./target/memfill.arm64

      - name: Publish GH Release
        uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: memfill ${{ github.ref_name }}
          artifacts: "target/memfill.amd64,target/memfill.arm64,LICENSE"
          generateReleaseNotes: true
